### ISSUE TITLE
Transformed config file not being created

### ISSUE THREAD

**Issue by GuyHarwood** [a11smiles/gulp-config-transform#1]
I cant get this to produce a transformed configuration file.

I added gulp error handling but nothing is bubbling up.

I have reproduced the issue in a small example  - https://github.com/GuyHarwood/gulp-config-transform-bug

maybe you can spot something obvious.

Thanks in advance for any input

**Comment by a11smiles** [comment]
will take a look this weekend - under a deadline at the moment.  First thought, have you tried running Visual Studio as an Administrator?

**Comment by GuyHarwood** [comment]
ahh, i'm running from command line, without admin.

Will try that now....

**Comment by GuyHarwood** [comment]
that worked, can't believe i didn't think to try 😄 

Will update the readme and send you a PR 👍

**Comment by GuyHarwood** [comment]
So yesterday's success was unfortunately a false positive.

Can you confirm on the usage, as it looks different to a standard gulp plugin.

The example given is....

```
var config-transform = require('gulp-config-transform');

gulp.task('transform', function() {
    var options = { 
          transform : 'Web.Debug.config' }

    config-transform(options);  
});
```

But normally a gulp plug-in would be piped the input, such as....

```
var config-transform = require('gulp-config-transform');

gulp.task('transform', function() {
    var options = { 
          transform : 'Web.Debug.config' }

return gulp.src('source').pipe(config-transform(options)).dest('output');
});
```

I am about to debug it, but if you could confirm usage that would be helpful 👍

**Comment by younggrr** [comment]
I am also having the same issue, running Visual Studio 2015 as admin and executing with the Task Runner Explorer.  No output.  Here is my code:

```
var configTransform = require('gulp-config-transform');
gulp.task('transform-config-prod', function () {

    var options = {
        config: './Web.config',
        transform: './Web.Release.config',
        destination: './dist/Web.config'
    };
    configTransform(options);

});
```

**Comment by a11smiles** [comment]
@GuyHarwood the usage of the first is correct.  It doesn't use pipes as gulp actually kicks off a child process using MSBuild in order to do the transformation.

**Comment by a11smiles** [comment]
@GuyHarwood @younggrr there's a build going out now (0.2.27) that will fix this.  I refactored the plugin a while back to give it more flexibility.  The `options` variable was a global variable at that point.  Unfortunately, after the refactor, on line 90, I was mistakenly overwriting your passed-in options with the default options.  I've now created a local `_options` variable to differentiate between the two.  Please verify the fix works in your environments.

**Comment by younggrr** [comment]
@a11smiles I updated the package and tried running my task again but still with no success.  The '_msbuild.proj' seems to contain the correct paths though.

```
<Project ToolsVersion="4.0" DefaultTargets="Demo" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask TaskName="TransformXml" AssemblyFile="C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.Tasks.dll"/>
    <Target Name="Transform">
        <TransformXml Source="./Web.config" Transform="./Web.Release.config" Destination="./dist/Web.config"/>
    </Target>
</Project>
```

**Comment by a11smiles** [comment]
have you tried manually running msbuild against the project file?

`<pathToMsBuild> ./_msbuild.proj /t:Transform`

**Comment by a11smiles** [comment]
and since your assembly file is using `v14.0`, you'll want to make sure you're using the same msbuild path

**Comment by younggrr** [comment]
Running msBuild (v14.0) manually produced the correct result.   I tried manually specifying the 'msBuildPath' option but still no success running through the plugin.

**Comment by a11smiles** [comment]
Are you running gulp as part of VS or part of an automated build process?  Either way, it seems as if this is a permissions/identity issue.

**Comment by GuyHarwood** [comment]
I am still getting the same issue, even when running from cmd as administrator.

Try me repro, see if you get the same.  i have updated it to consume your latest package version - https://github.com/GuyHarwood/gulp-config-transform-bug

**Comment by GuyHarwood** [comment]
Running `<pathToMsBuild> ./_msbuild.proj /t:Transform`  produced errors in my transform, which i fixed and it then produced a transformed file.

However i still don't get an output when running the plugin.  It's as if it doesn't execute MsBuild.

Adding console.log in your index.js for _options and _project outputs the following...

```
C:\Users\guy\dev\configTransformTest>gulp
[09:50:15] Using gulpfile ~\dev\configTransformTest\gulpfile.js
[09:50:15] Starting 'default'...
_options...
{ config: './Web.Config',
  transform: './Web.Release.config',
  destination: './My.Config',
  netVersion: '4',
  framework: 'x64',
  msBuildPath: 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\msbuild.exe
',
  assemblyFile: 'C:\\Program Files (x86)\\MSBuild\\Microsoft\\VisualStudio\\v10.
0\\Web\\Microsoft.Web.Publishing.Tasks.dll' }
_project...
<Project ToolsVersion="4.0" DefaultTargets="Demo" xmlns="http://schemas.microsof
t.com/developer/msbuild/2003"><UsingTask TaskName="TransformXml" AssemblyFile="C
:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0\Web\Microsoft.Web.Pub
lishing.Tasks.dll"/><Target Name="Transform"><TransformXml Source="./Web.Config"
 Transform="./Web.Release.config" Destination="./My.Config"/></Target></Project>

[09:50:15] Finished 'default' after 27 ms
C:\Users\guy\dev\configTransformTest>gulp
[09:50:15] Using gulpfile ~\dev\configTransformTest\gulpfile.js
[09:50:15] Starting 'default'...
_options...
{ config: './Web.Config',
  transform: './Web.Release.config',
  destination: './My.Config',
  netVersion: '4',
  framework: 'x64',
  msBuildPath: 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\msbuild.exe
',
  assemblyFile: 'C:\\Program Files (x86)\\MSBuild\\Microsoft\\VisualStudio\\v10.
0\\Web\\Microsoft.Web.Publishing.Tasks.dll' }
_project...
<Project ToolsVersion="4.0" DefaultTargets="Demo" xmlns="http://schemas.microsof
t.com/developer/msbuild/2003"><UsingTask TaskName="TransformXml" AssemblyFile="C
:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0\Web\Microsoft.Web.Pub
lishing.Tasks.dll"/><Target Name="Transform"><TransformXml Source="./Web.Config"
 Transform="./Web.Release.config" Destination="./My.Config"/></Target></Project>

[09:50:15] Finished 'default' after 27 ms
```

**Comment by a11smiles** [comment]
@GuyHarwood thanks for the sample project, i think I have a fix for it, but I need to do a little more testing.  I will let you know later today.

**Comment by a11smiles** [comment]
apparently the gulp.shell module was blacklisted and therefore was no longer being called with the "installable" gulp.  Leave it to Visual Studio to use an older gulp version that was still running the module. :disappointed:

**Comment by a11smiles** [comment]
@GuyHarwood thanks for the sample project. it was a great help to resolving this.

**Comment by a11smiles** [comment]
fixed w/ build 0.2.29

**Comment by GuyHarwood** [comment]
@a11smiles You're welcome, thanks for sorting out the fix

Can confirm it's working for me

**Comment by younggrr** [comment]
@a11smiles Fix works for me also, thank you!
